export const stacks = [
  { name: "JavaScript", category: "FE", isPopular: true, number: 1 },
  { name: "TypeScript", category: "FE", isPopular: true, number: 2 },
  { name: "React", category: "FE", isPopular: true, number: 3 },
  { name: "Vue", category: "FE", isPopular: true, number: 4 },
  { name: "Svelte", category: "FE", isPopular: true, number: 5 },
  { name: "NextJs", category: "FE", isPopular: true, number: 6 },
  { name: "NodeJs", category: "BE", isPopular: true, number: 7 },
  { name: "Java", category: "BE", isPopular: true, number: 8 },
  { name: "Spring", category: "BE", isPopular: true, number: 9 },
  { name: "Go", category: "BE", isPopular: true, number: 10 },
  { name: "Nestjs", category: "BE", isPopular: true, number: 11 },
  { name: "Kotlin", category: "BE, Mobile", isPopular: false, number: 12 },
  { name: "Express", category: "BE", isPopular: false, number: 13 },
  { name: "MySQL", category: "BE", isPopular: false, number: 14 },
  { name: "MongoDB", category: "BE", isPopular: false, number: 15 },
  { name: "Python", category: "BE", isPopular: false, number: 16 },
  { name: "Django", category: "BE", isPopular: false, number: 17 },
  { name: "Php", category: "BE", isPopular: false, number: 18 },
  { name: "GraphQL", category: "BE", isPopular: false, number: 19 },
  { name: "Firebase", category: "BE", isPopular: false, number: 20 },
  { name: "Flutter", category: "Mobile", isPopular: false, number: 21 },
  { name: "Swift", category: "Mobile", isPopular: false, number: 22 },
  { name: "ReactNative", category: "Mobile", isPopular: false, number: 23 },
  { name: "Unity", category: "Mobile", isPopular: false, number: 24 },
  { name: "Aws", category: "ETC", isPopular: false, number: 25 },
  { name: "Kubernetes", category: "ETC", isPopular: false, number: 26 },
  { name: "Docker", category: "ETC", isPopular: false, number: 27 },
  { name: "Git", category: "ETC", isPopular: false, number: 28 },
  { name: "Figma", category: "ETC", isPopular: false, number: 29 },
  { name: "Zeplin", category: "ETC", isPopular: false, number: 30 },
  { name: "Jest", category: "ETC", isPopular: false, number: 31 },
  { name: "C", category: "ETC", isPopular: false, number: 32 },
];
