export const stacks = [
  { name: "JavaScript", category: "FE", isPopular: true },
  { name: "TypeScript", category: "FE", isPopular: true },
  { name: "React", category: "FE", isPopular: true },
  { name: "Vue", category: "FE", isPopular: true },
  { name: "Svelte", category: "FE", isPopular: true },
  { name: "NextJs", category: "FE", isPopular: true },
  { name: "NodeJs", category: "BE", isPopular: true },
  { name: "Java", category: "BE", isPopular: true },
  { name: "Spring", category: "BE", isPopular: true },
  { name: "Go", category: "BE", isPopular: true },
  { name: "Nestjs", category: "BE", isPopular: true },
  { name: "Kotlin", category: "BE, Mobile", isPopular: false },
  { name: "Express", category: "BE", isPopular: false },
  { name: "MySQL", category: "BE", isPopular: false },
  { name: "MongoDB", category: "BE", isPopular: false },
  { name: "Python", category: "BE", isPopular: false },
  { name: "Django", category: "BE", isPopular: false },
  { name: "Php", category: "BE", isPopular: false },
  { name: "GraphQL", category: "BE", isPopular: false },
  { name: "Firebase", category: "BE", isPopular: false },
  { name: "Flutter", category: "Mobile", isPopular: false },
  { name: "Swift", category: "Mobile", isPopular: false },
  { name: "ReactNative", category: "Mobile", isPopular: false },
  { name: "Unity", category: "Mobile", isPopular: false },
  { name: "AWS", category: "ETC", isPopular: false },
  { name: "Kubernetes", category: "ETC", isPopular: false },
  { name: "Docker", category: "ETC", isPopular: false },
  { name: "Git", category: "ETC", isPopular: false },
  { name: "Figma", category: "ETC", isPopular: false },
  { name: "Zeplin", category: "ETC", isPopular: false },
  { name: "Jest", category: "ETC", isPopular: false },
  { name: "C", category: "ETC", isPopular: false },
];
